In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1, 2, 3])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6.5]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [10]:
a1.dtype

dtype('int64')

In [11]:
a2.dtype

dtype('float64')

In [12]:
a1.size

3

In [13]:
a2.size

6

In [14]:
type(a1)

numpy.ndarray

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)

In [16]:
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating arrays

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)

In [24]:
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [26]:
random_array

array([[7, 4, 6, 8, 8],
       [8, 3, 4, 4, 3],
       [2, 6, 9, 8, 8]], dtype=int32)

In [27]:
random_array.size

15

In [28]:
len(random_array)

3

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))

In [31]:
random_array_2

array([[0.98129685, 0.85155289, 0.31366718],
       [0.2685055 , 0.3816224 , 0.15255939],
       [0.72978546, 0.82596083, 0.37133387],
       [0.39925537, 0.41269113, 0.29304667],
       [0.44803342, 0.6147391 , 0.90950621]])

In [38]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.22692437, 0.62085613, 0.4153138 ],
       [0.03486366, 0.03302775, 0.02602695],
       [0.3771299 , 0.97853712, 0.05161869],
       [0.73196663, 0.08207906, 0.98870746],
       [0.99014076, 0.24892788, 0.44850452]])

In [43]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [40]:
random_array_4

array([[3, 2, 7],
       [6, 6, 9],
       [1, 5, 5],
       [9, 6, 2],
       [9, 9, 1]], dtype=int32)

In [41]:
test = pd.DataFrame(random_array_4)

In [42]:
test

   0  1  2
0  3  2  7
1  6  6  9
2  1  5  5
3  9  6  2
4  9  9  1

In [48]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [49]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

## 4. Manipulating and comparing arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [53]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
ones = np.ones(3)

In [55]:
ones

array([1., 1., 1.])

In [56]:
a1 + ones

array([2., 3., 4.])

In [57]:
a1 - ones

array([0., 1., 2.])

In [58]:
a1 * ones

array([1., 2., 3.])