In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1, 2, 3])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6.5]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [10]:
a1.dtype

dtype('int64')

In [11]:
a2.dtype

dtype('float64')

In [12]:
a1.size

3

In [13]:
a2.size

6

In [14]:
type(a1)

numpy.ndarray

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)

In [16]:
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating arrays

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)

In [24]:
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [26]:
random_array

array([[1, 5, 7, 5, 9],
       [1, 5, 1, 8, 7],
       [3, 3, 1, 5, 4]], dtype=int32)

In [27]:
random_array.size

15

In [28]:
len(random_array)

3

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))

In [31]:
random_array_2

array([[0.87864181, 0.05155126, 0.95235012],
       [0.0127014 , 0.7673674 , 0.4520062 ],
       [0.07318731, 0.47630234, 0.23947278],
       [0.83291088, 0.95626919, 0.14870339],
       [0.03668322, 0.57415229, 0.24349363]])

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.2429764 , 0.53157752, 0.62626029],
       [0.26238443, 0.34466324, 0.17431219],
       [0.08167041, 0.40654261, 0.95808084],
       [0.20022285, 0.98827315, 0.731651  ],
       [0.24203428, 0.21118537, 0.63926698]])

In [33]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [34]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [35]:
test = pd.DataFrame(random_array_4)

In [36]:
test

   0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [37]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

## 4. Manipulating and comparing arrays

### Arithmetic

In [39]:
a1

array([1, 2, 3])

In [40]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
ones = np.ones(3)

In [42]:
ones

array([1., 1., 1.])

In [43]:
a1 + ones

array([2., 3., 4.])

In [44]:
a1 - ones

array([0., 1., 2.])

In [45]:
a1 * ones

array([1., 2., 3.])

### Aggregation

Aggregation = performing the same operation on a number of things

In [47]:
listy_list = [1, 2, 3]

In [48]:
type(listy_list)

list

In [49]:
sum(listy_list)

6

In [50]:
np.sum(a1)

np.int64(6)

Use python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [51]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [54]:
massive_array[:10]

array([0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923,
       0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837])

In [55]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

9.83 ms ± 824 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.5 μs ± 3.12 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [56]:
np.mean(a2)

np.float64(3.5833333333333335)

In [57]:
np.max(a2)

np.float64(6.5)

In [58]:
np.min(a2)

np.float64(1.0)

In [59]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

np.float64(3.368055555555556)

In [60]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.8352262954621035)

In [62]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

np.float64(1.8352262954621035)